POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.amazon.com/dp/B07YMNLXL3?ref=dacx_dp_8502751740701_2814399000301&me=ATVPDKIKX0DER&aaxitk=-o6wOgbuHvyJVI3HYBLvlA"
}